### ISSUE TITLE
support model data in HdbPoet

### ISSUE THREAD

**Issue by ktarbet** [usbr/HdbPoet#5]
To start this would require using m_tables instead of r_tables.  At the highest level.
 
static string[] r_tables = { "r_instant", "r_hour", "r_day", "r_month", "r_year", "r_wy","r_base" };
static string[] m_tables = { "m_undefined", "m_hour", "m_day", "m_month", "m_year", "m_wy","m_undefined" };
public static string[] r_names = { "instant", "hour", "day", "month", "year", "wy" ,"base"};

**Comment by ktarbet** [comment]
I've created a new branch [model data](https://github.com/usbr/HdbPoet/tree/model_data)

**Comment by tjrocha** [comment]
The model_data branch now supports CRUD capabilities for data in the M-tables. Steps below show use for the read function from the main interface.

1. Put a check in the Modeled Data checkbox
2. Specify a model run id in the textbox next to it
3. Click on create list of sites.
4. Select sites from the tree taking note of the date selection since most of the modeled data is in the future
5. Click on the Table tab to download data and populate the POET spreadsheet

Changes to the interface include rearranging buttons and boxes along with fixing index sequences for the {TAB} key. Additions to OpenSourceDependency/Hdb.Procedures.cs were made for methods to call HDB stored procedures for inserting, updating, and deleting entries in the M-tables.

Additional work required for:
1. Redirect the saving/updating of M-table data in the POET Table tab to the newly added method HdbPoet.Hdb.Instance.modify_m_table(mrid, sdi, t1, t2, value, interval, true)
2. Add the capability in the POET Table interface to delete data and call the newly added method HdbPoet.Hdb.Instance.delete_from_mtable(mrid, sdi, t1, t2, interval)

**Comment by ktarbet** [comment]
I suggest we consolidate some of the duplicate code in 
OpenSourceDependency/Hdb.Procedures.cs and LicensedDependency/Hdb.Procedures.cs

We could create file a  Hdb.CommonProcedures  (partial class HDB) that has code the works with either database provider - and store this at root directory level.  The main reason we have two files is the OracleDbType.Varchar2 in the Oracle provider which is different than the DevArt OracleDbType.VarChar.     There is some code we could move to the Hdb.CommonProcedures file without any pain.

**Comment by tjrocha** [comment]
Added capability to Update and Delete records from the modeled tables. After querying the modeled data tables, editing/updating/deleting entries in the POET Table tab and pressing the save icon now sends the changes to HDB. Have to ensure that user is added on the REF_USER_GROUPS table in HDB (USER_NAME=log-in, GROUP_NAME=DBA, ACTIVE_FLAG=Y)to allow for editing in POET.

Additional work needed for:
1. Add an icon/interface for the creation/insertion of a new row in the POET Table tab so that new records may be created and passed on to HDB.
2. Would an interface to query/edit/create model run ids be useful now that we are working with the model tables? Should this go on another tab or a pop-up?

**Comment by ktarbet** [comment]
Can you insert new data by setting the dates to create blank records?

**Comment by ktarbet** [comment]
A beta version of model_data branch is here:  http://www.usbr.gov/pn/hydromet/poet/
